'use client'
import { Info } from 'lucide-react'
import Tooltip from './Tooltip'

export interface MetricDef {
  label: string
  what: string          // plain-English "what does this count"
  formula?: string      // optional formula / calculation
  thresholds?: { range: string; meaning: string; color: string }[]
  tip?: string          // extra pro-tip
}

interface Props {
  metric: MetricDef
  /** Tooltip position. Default 'top'. */
  position?: 'top' | 'bottom' | 'left' | 'right'
  size?: number
}

/**
 * A small ⓘ icon that reveals a rich metric-definition tooltip on hover.
 *
 * Usage:
 *   <MetricInfo metric={METRICS.qualityScore} />
 */
export default function MetricInfo({ metric, position = 'top', size = 12 }: Props) {
  const content = (
    <div className="space-y-2" style={{ maxWidth: 280 }}>
      <p className="font-semibold text-white text-[12px]">{metric.label}</p>
      <p className="text-gray-300 text-[11px] leading-relaxed">{metric.what}</p>

      {metric.formula && (
        <div className="bg-gray-800 rounded px-2 py-1">
          <span className="text-[10px] font-mono text-blue-300">{metric.formula}</span>
        </div>
      )}

      {metric.thresholds && metric.thresholds.length > 0 && (
        <div className="space-y-1">
          <p className="text-[10px] text-gray-400 uppercase tracking-wider">Thresholds</p>
          {metric.thresholds.map(t => (
            <div key={t.range} className="flex items-center gap-2">
              <span className={`text-[10px] font-semibold shrink-0 ${t.color}`}>{t.range}</span>
              <span className="text-[11px] text-gray-300">{t.meaning}</span>
            </div>
          ))}
        </div>
      )}

      {metric.tip && (
        <p className="text-[10px] text-yellow-300 border-t border-gray-700 pt-1.5">
          💡 {metric.tip}
        </p>
      )}
    </div>
  )

  return (
    <Tooltip content={content} position={position} maxWidth={300}>
      <Info
        size={size}
        className="text-gray-400 hover:text-blue-400 transition-colors cursor-help shrink-0"
        aria-label={`Info: ${metric.label}`}
      />
    </Tooltip>
  )
}

// ── Metric definitions ────────────────────────────────────────────────────────
// Import and use these anywhere a MetricInfo icon is needed.

export const METRICS: Record<string, MetricDef> = {
  qualityScore: {
    label: 'Quality Score',
    what: 'Severity-weighted score showing how healthy your data is. Starts at 100 and loses points for each failing rule based on its severity.',
    formula: '100 − Σ(penalty per failing rule)',
    thresholds: [
      { range: '≥ 95%', meaning: 'Excellent — all critical checks passing', color: 'text-green-400' },
      { range: '85–94%', meaning: 'Good — minor issues present', color: 'text-yellow-400' },
      { range: '60–84%', meaning: 'Warning — significant failures', color: 'text-orange-400' },
      { range: '< 60%', meaning: 'Critical — immediate action needed', color: 'text-red-400' },
    ],
    tip: 'A single critical failure deducts 25 pts. Fix critical rules first for the biggest score gains.',
  },
  scoreDelta: {
    label: 'Score Trend',
    what: "Change in quality score compared to yesterday's score.",
    formula: "today's score − yesterday's score",
    thresholds: [
      { range: '▲ positive', meaning: 'Quality improved', color: 'text-green-400' },
      { range: '▼ negative', meaning: 'Quality degraded — investigate failures', color: 'text-red-400' },
      { range: 'No change', meaning: 'Score unchanged (< 0.05% difference)', color: 'text-gray-400' },
    ],
    tip: 'A sudden drop often means a new rule failed or data volume changed unexpectedly.',
  },
  domainCount: {
    label: 'Domains Monitored',
    what: 'Number of active business domains registered in the platform (e.g. Revenue, Finance, HR).',
    tip: 'Go to Admin → Domain Management to add or edit domains.',
  },
  tablesMonitored: {
    label: 'Tables Monitored',
    what: 'Count of Snowflake tables that have been registered and have at least one active rule assigned.',
    tip: 'Tables without active rules do not contribute to the quality score.',
  },
  activeRules: {
    label: 'Active Rules',
    what: 'Data quality rules with status "active". Only active rules execute on schedule or when triggered manually.',
    tip: 'Rules in draft or pending_review status do not run until approved.',
  },
  openAlerts: {
    label: 'Open Alerts',
    what: 'Alerts generated by failing rules that have not yet been acknowledged, resolved, or ignored.',
    thresholds: [
      { range: '0', meaning: 'Healthy — no unresolved issues', color: 'text-green-400' },
      { range: '1–4', meaning: 'Some attention needed', color: 'text-yellow-400' },
      { range: '≥ 5', meaning: 'High — multiple issues need action', color: 'text-red-400' },
    ],
    tip: 'Alerts deduplicate within 4 hours — repeated failures do not spam you.',
  },
  passedToday: {
    label: 'Passed Today',
    what: 'Rules whose most recent execution today returned a "passed" status — zero rows violated the check.',
  },
  failedToday: {
    label: 'Failed Today',
    what: 'Rules that returned "failed" or "error" in their most recent execution today.',
    tip: 'Click a failing rule to see the executed SQL, failed row samples, and AI explanation.',
  },
  criticalFailures: {
    label: 'Critical Failures',
    what: 'Count of rules with severity "critical" that are currently failing. These represent the highest-risk data issues.',
    thresholds: [
      { range: '0', meaning: 'No critical issues — great!', color: 'text-green-400' },
      { range: '≥ 1', meaning: 'Requires immediate investigation', color: 'text-red-400' },
    ],
    tip: 'Critical failures deduct 25 pts each from the quality score.',
  },
  passRateToday: {
    label: 'Pass Rate Today',
    what: 'Simple ratio of passed rules to total rules executed today. Different from quality score — this is unweighted.',
    formula: 'passed / (passed + failed) × 100',
    thresholds: [
      { range: '100%', meaning: 'All rules passing', color: 'text-green-400' },
      { range: '< 90%', meaning: 'More than 10% of rules failing', color: 'text-red-400' },
    ],
  },
  runsScore: {
    label: 'Run Score',
    what: 'Per-execution quality score — measures what fraction of individual rows passed the rule.',
    formula: 'max(0, 100 − failed_rows / total_rows × 100)',
    tip: 'A 0.01% failure on a 10M-row table may still be critical depending on severity.',
  },
  failedRows: {
    label: 'Failed Rows',
    what: 'Number of individual rows in Snowflake that violated the rule condition in this run.',
  },
  totalRows: {
    label: 'Rows Scanned',
    what: 'Total rows the rule SQL evaluated. For row-level checks (null, regex) this is the whole table. For aggregates (freshness, volume) it may be 1.',
  },
  deltaBadge: {
    label: 'Δ Change vs Last Run',
    what: "Percentage-point change in the run score compared to the same rule's immediately preceding run.",
    formula: 'current_score − previous_score',
    thresholds: [
      { range: '▲', meaning: 'Quality improved since last run', color: 'text-green-400' },
      { range: '▼', meaning: 'Quality degraded — investigate', color: 'text-red-400' },
    ],
  },
}
